#@formatter:off
name: test_task_weather
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  retry: ^3.1.2
  encrypt: ^5.0.3
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  flutter_native_splash: ^2.3.3
  collection: ^1.17.1
  flutter_dotenv: ^5.1.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_screenutil: ^5.9.0
  loader_overlay: ^2.3.2
  go_router: ^10.1.0
  intl: ^0.18.0
  intl_utils: ^2.8.4
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_svg: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_google_places_hoc081098: ^1.2.0


flutter:
  uses-material-design: true
  

    # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/launcher_icons/
    - assets/map/
    - assets/icons/
    #   - images/a_dot_ham.jpeg


    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages




flutter_icons:
  image_path: "assets/launcher_icons/ic_launcher.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"
  windows:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"
  macos:
    generate: true
    image_path: "assets/launcher_icons/ic_launcher.png"



flutter_intl:
  enabled: true
  arb_dir: lib/core/app/localization/l10n
  output_dir: lib/core/app/localization/generated
  
#generated with mason